export const action_types = {
  GET_REPORT_SUCCESS: 'GET_REPORT_SUCCESS',
  DOWNLOAD_REPORT_SUCCESS: 'DOWNLOAD_REPORT_SUCCESS',
  GET_AUTO_REPORT_SUCCESS: 'GET_AUTO_REPORT_SUCCESS',
  UPDATE_REPORT_SUCCESS: 'UPDATE_REPORT_SUCCESS',
};
