const action_types = {
  'GET-FACILITIES-LIST': 'GET-FACILITIES-LIST',
  'GET-MANAGERS-LIST': 'GET-MANAGERS-LIST',
  'ADD-FACILITY': 'ADD-FACILITY',
  'GET-ALL-FACILITIES-LIST': 'GET-ALL-FACILITIES-LIST',
  UPDATE_FACILITY: 'UPDATE_FACILITY',
  'DELETE-FACILITY': 'DELETE-FACILITY',
};

export default action_types;
